const mongoose = require("mongoose");

const playerSchema = new mongoose.Schema({
    _id: mongoose.Schema.Types.ObjectId,
    active: Boolean,
    age: mongoose.Schema.Types.Mixed,
    birth_city: {type: String, default: null},
    birth_country: {type: String, default: null},
    birth_date: String,
    birth_state: {type: String, default: null},
    college: String,
    depth_chart_order: Number,
    depth_chart_position: {type: String, default: null},
    espn_id: Number,
    fantasy_data_id: Number,
    fantasy_positions: mongoose.Schema.Types.Mixed,
    first_name: String,
    full_name: String,
    gsis_id: {type: String, default: null},
    hashtag: String,
    height: String,
    high_school: String,
    injury_body_part: {type: String, default: null},
    injury_notes: {type: String, default: null},
    injury_start_date: {type: String, default: null},
    injury_status: {type: String, default: null},
    last_name: String,
    metadata: { type: mongoose.Schema.Types.Mixed, default: null },
    news_updated: Number,
    number: {type: Number, default: null},
    pandascore_id: {type: String, default: null},
    player_id: String,
    position: String,
    position_rank: {type: String, default: null},
    practice_description: {type: String, default: null},
    practice_participation: {type: String, default: null},
    rank: {type: String, default: null},
    rotowire_id: Number,
    rotoworld_id: Number,
    search_first_name: String,
    search_full_name: String,
    search_last_name: String,
    search_rank: Number,
    sport: String,
    sportradar_id: String,
    status: String,
    swish_id: {type: Number, default: null},
    team: String,
    tier: {type: String, default: null},
    trend: {type: String, default: null},
    value: {type: String, default: null},
    weight: String,
    years_exp: Number,
    yahoo_id: Number,
    stats_id: Number,
});


module.exports = mongoose.model("Player", playerSchema);